services:
  - type: web
    name: deepface-app
    runtime: python
    buildCommand: pip install -r requirements.txt && python preload_models.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
